### ISSUE TITLE
zeroin error

### ISSUE THREAD

**Issue by tommyfuu** [mengyu-he/MIDASim#1]
hi!

I am trying to use MIDAS to simulate a dataset based on a published dataset, but ran into an error when running the line `fitted_c0b0 = Midas.modify(fitted,
                            lib.size = rep(10000,n))`.

Here's the whole error traceback. 

```
Error in .zeroin(f, a, b, maxiter = maxiter, tol = tol) :
zeroin: zero point could not be bracketed
6.
stop("zeroin: zero point could not be bracketed")
5.
.zeroin(f, a, b, maxiter = maxiter, tol = tol)
4.
pracma::fzero(fun = equa, x = c(-100, 100), tol = 10^-10)
3.
solver_mu_sigma(mu0 = fitted$mu, eta0 = rep(0, n.sample), Ztotal = Ztotal,
sample.1.prop = fitted$sample.1.prop, taxa.1.prop = obs.taxa.1.prop,
ids.left = ids.left, n.sample = n.sample, n.rm = n.rm)
2.
Midas.modify(fitted, lib.size = rep(10000, n))
1.
midas_bc_biovar(otu_original, n, bin_corr, cond_effect, batch_effect,
"./QinJ_2012_relab.csv")
```

Was wondering if you have run into similar errors? Thanks!

**Comment by mengyu-he** [comment]
Hi, sorry that I just see this message. I wonder if you could share the fitted data so I could reproduce and look into the error. Thanks!

**Comment by tommyfuu** [comment]
hey! do you have an email address so I can share the data and code? I actually have another error related to this error now - i am also working with Jiuyao and Wodan on a microbiome batch correction paper where I am simulating data with MIDAS, it will be nice to get in touch to make it work! Thanks!
