### ISSUE TITLE
Error when using nonparametric mode (Error in -fitted.modified$mu.est)

### ISSUE THREAD

**Issue by CassandraHjo** [mengyu-he/MIDASim#3]
I tried to follow your steps from the README with the non parametric mode, but when I try to simulate I get an error. I do not get this error when using the parametric mode. 

Here is my code:

```
library(MIDASim)
library(HMP2Data)

data("count.ibd")

IBD16S()

count.ibd = t(IBD16S_mtx[, colSums(IBD16S_mtx)>3000] )
count.ibd = count.ibd[, colSums(count.ibd>0)>1]

count.ibd.setup = MIDASim.setup(count.ibd, mode = 'nonparametric')

beta <- 0.1
new.mean.rel.abund <- count.ibd.setup$mean.rel.abund
new.mean.rel.abund[1:10] <- exp(beta) * new.mean.rel.abund[1:10]
new.mean.rel.abund <- new.mean.rel.abund / sum(new.mean.rel.abund)

new.taxa.1.prop <- count.ibd.setup$taxa.1.prop 
new.taxa.1.prop[1:10] <- new.taxa.1.prop[1:10] + 0.05

r <- sum(new.taxa.1.prop) / sum(count.ibd.setup$taxa.1.prop)
new.sample.1.prop <- count.ibd.setup$sample.1.prop * r

count.ibd.modified <- MIDASim.modify(count.ibd.setup,
                                    mean.rel.abund = new.mean.rel.abund,
                                    taxa.1.prop = new.taxa.1.prop,
                                    sample.1.prop = new.sample.1.prop)

simulated.data <- MIDASim(count.ibd.modified)
```

Error message when running MIDASim():
`Error in -fitted.modified$mu.est : invalid argument to unary operator`

What is the main differences between the two modes?

**Comment by mengyu-he** [comment]
Hi,

Thank you for pointing out this issue. It has now been addressed, and I recommend re-installing the package for the updated functionality.

The two modes differ in the ways of modeling the marginal distribution of relative abundances. The nonparametric mode uses an empirical distribution of observed relative abundances. This mode is ideal for reproducing the template data when there is no need to modify the library sizes or taxa features.

The parametric mode employs a generalized gamma distribution for modeling relative abundances. This mode is more useful and flexible when modifying model parameters (library sizes or taxa features), as it provides coordinated changes in these parameters.

For more details, you could refer to our manuscript on biorxiv by the following link,

https://www.biorxiv.org/content/10.1101/2023.03.23.533996v2

Please let me know if you have further questions. Thanks,

Best,
Mengyu

**Comment by CassandraHjo** [comment]
Thanks. The error seems to be gone now. 

Is it possible to set a random seed, or will the simulation whn using parametric mode always give the same results?

**Comment by mengyu-he** [comment]
The function MIDASim() in either mode will give different results every time you run it. Basically MIDASim.setup() and MIDASim.modify() fit the model to your provided template data, and MIDASim() will generate random samples from the fitted model.

**Comment by CassandraHjo** [comment]
But there is no way to controll the randomness?

**Comment by mengyu-he** [comment]
You could control the randomness by setting a specific seed before running MIDASim(). For example, you will get the same simulated datasets if you run the following: 

set.seed(1)
simulated.data <- MIDASim(count.ibd.modified)

**Comment by CassandraHjo** [comment]
Thanks so much for the help and the fast replies
