### ISSUE TITLE
Error in uniroot when running MIDASim.setup()

### ISSUE THREAD

**Issue by CassandraHjo** [mengyu-he/MIDASim#4]
I am trying to use my own data as template data for the simulation, but I get this error message

```
Error in uniroot(f = sigma.eqn, interval = c(0, 2 * abs(K)), extendInt = "upX",  :
    f.lower = f(lower) is NA
```

What does it mean?

This is my code:

`count.crc.setup = MIDASim.setup(count.data, mode = 'parametric')`

My data contains samples as rows and taxa as columns, and all values are numeric. The table is a count table with metagenome data. The taxa are MAGs and the values correspond to the number of times a MAG is observed in a sample. Here is a subset of the data:

![image](https://github.com/mengyu-he/MIDASim/assets/132651748/27059d04-f474-4db7-bd55-11a54eccb7e1)

I am also wondering why the number of taxa have to be larger than the number of samples? In my original data the number of samples are larger than the number of MAGs.

**Comment by mengyu-he** [comment]
Hi, based on the error you presented, it is likely that some of the columns in your data containing all zeros. I wonder if you could check and remove those columns and retry the simulation.

For your second question, it is not required to have more taxa than samples, but in most microbiome datasets, the number of taxa is larger than the number of samples. The MIDASim function is designed to give an message just in case that the users accidentally swapped the rows and columns of the data input.
