### ISSUE TITLE
No vignettes found by browseVignettes("MIDASim")

### ISSUE THREAD

**Issue by artcmd** [mengyu-he/MIDASim#5]
Hello, I'm not an R user but interested in this package. Could you guide me on the initial setup?

I installed MIDASim on R version 4.1.2 and couldn't load it.

```
> library(MIDASim)
>
> browseVignettes("MIDASim")
No vignettes found by browseVignettes("MIDASim")
```

**Comment by mengyu-he** [comment]
Hi, 

Could you try the following,

`
devtools::install_github("mengyu-he/MIDASim", build_vignettes = T, force = T)
`
`browseVignettes("MIDASim")`

Please let me know if it does not work. Thanks.

**Comment by artcmd** [comment]
Thank you! It works for us.

**Comment by artcmd** [comment]
Thank you! It works for us.
